AdventureWorksStore.WebUI/Models/CartListViewModel.cs
using AdventureWorksStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorksStore.WebUI.Models
{
    public class CartListViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

AdventureWorksStore.WebUI/Models/PageInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorksStore.WebUI.Models
{
    public class PageInfo
    {
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int TotalItems { get; set; }

        public int TotalPages
        {
            get
            {
                return (int)Math.Ceiling((decimal)TotalItems / PageSize);
            }
        }
    }
}

AdventureWorksStore.WebUI/Models/ProductsListViewModel.cs
using AdventureWorksStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorksStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PageInfo PageInfo { get; set; }

        public string CurrentCategory { get; set; }
    }
}

AdventureWorksStore.WebUI/Controllers/AdminController.cs
using AdventureWorksStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdventureWorksStore.WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository repository;
        public AdminController(IProductRepository iRepository)
        {
            repository = iRepository;
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit()
        {
            return View();
        }
    }
}

AdventureWorksStore.WebUI/Controllers/CartController.cs
using AdventureWorksStore.Domain.Abstract;
using AdventureWorksStore.Domain.Entities;
using AdventureWorksStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdventureWorksStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcess order;
        public CartController(IProductRepository iProducRepository, IOrderProcess iOrder)
        {
            repository = iProducRepository;
            order = iOrder;
        }
        // GET: Cart
        public ActionResult Index(Cart cart, string returnUrl)
        {
            return View(new CartListViewModel { Cart = cart, ReturnUrl = returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public RedirectToRouteResult AddToCart(Cart cart, Int32 productId, string returnUrl)
        {
            var product = repository.Products.FirstOrDefault(s => s.ProductID == productId);
            if (product != null)
            {
                cart.AddToCart(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, Int32 productId, string returnUrl)
        {
            var product = repository.Products.FirstOrDefault(s => s.ProductID == productId);
            if (product != null)
            {
                cart.RemoveFromCart(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingInfo)
        {
            if (cart.CartItems.Any() == false)
            {
                ModelState.AddModelError("empty", "No Item In Cart");
            }
            if (ModelState.IsValid)
            {
                order.ProcessOrder(cart, shippingInfo);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingInfo);
            }
        }

        public Cart GetCart()
        {
            var cart = Session["Cart"];
            if (cart == null)
            {
                var newCart = new Cart();
                Session["Cart"] = newCart;
                return newCart;
            }
            else
            {
                return cart as Cart;
            }
        }
    }
}

AdventureWorksStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdventureWorksStore.Domain.Concrete;
using AdventureWorksStore.Domain.Abstract;

namespace AdventureWorksStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        public NavController(IProductRepository rep)
        {
            repository = rep;
        }
        // GET: Nav
        public PartialViewResult Menu(string category)
        {
            ViewBag.Category = category;
            return PartialView(repository.Products.Select(c => c.Category).Distinct());
        }
    }
}

AdventureWorksStore.WebUI/Controllers/ProductController.cs
using AdventureWorksStore.Domain.Abstract;
using AdventureWorksStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdventureWorksStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        private int PageSize = 10;
        public ProductController(IProductRepository iRepository)
        {
            repository = iRepository;
        }
        //
        // GET: /Product/
        public ViewResult List(string category = null, int page = 1)
        {
            ProductsListViewModel listViewModel = new ProductsListViewModel
            {
                PageInfo = new PageInfo { CurrentPage = page, PageSize = 10, TotalItems = category == null ? repository.Products.Count() : repository.Products.Where(s => s.Category == category).Count() },
                CurrentCategory = category,
                Products = repository.Products.Where(p => (category == null && p.Category != null) || p.Category == category).
                OrderBy(p => p.ProductID).
                Skip((page - 1) * PageSize).
                Take(PageSize)
            };
            return View(listViewModel);
        }
    }
}

AdventureWorksStore.WebUI/Views/Cart/Checkout.cshtml
@model AdventureWorksStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Checkout";
}

<h2>Check out now</h2> <p>Please enter your details, and we'll ship your goods right away!</p>
@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <h3>
        Ship To
    </h3>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(s => s.Name, new { @class = "form-control" })
    </div>
    <h3>Address</h3>
    <div class="form-group">
        <label>Line 1:</label>
        @Html.TextBoxFor(x => x.Line1, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Line 2:</label>
        @Html.TextBoxFor(x => x.Line2, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Line 3:</label>
        @Html.TextBoxFor(x => x.Line3, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>City:</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>State:</label>
        @Html.TextBoxFor(x => x.State, new { @class = "form-control" })
    </div>    <div class="form-group">
        <label>Zip:</label>

        @Html.TextBoxFor(x => x.Zip, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Country:</label>
        @Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
    </div>
    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)            Gift wrap these items
        </label>
    </div>    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Complete order" />

    </div>
}

AdventureWorksStore.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Completed";
}

<p>Thank you!</p>

AdventureWorksStore.WebUI/Views/Cart/Index.cshtml
@model AdventureWorksStore.WebUI.Models.CartListViewModel

@{
    ViewBag.Title = "Cart";
}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">SubTotal</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var c in Model.Cart.CartItems)
        {
            <tr>
                <td>
                    @Html.TextBox("quantity", c.Quantity, new { @class = "input-sm" })
                </td>
                <td>
                    @c.Product.Name
                </td>
                <td>
                    @c.Product.ListPrice.ToString("c")
                </td>
                <td>
                    @((c.Quantity * c.Product.ListPrice).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.HiddenFor(p => p.ReturnUrl)
                        @Html.Hidden("ProductId", c.Product.ProductID)
                        <input type="submit" value="Remove" class="btn btn-danger" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
            <td></td>
        </tr>
    </tfoot>
</table>
<div class="pull-center">
    @Html.ActionLink("Continue Shopping", "Index", new { requrnUrl = Request.Url.PathAndQuery }, new { @class = "btn btn-default btn-primary" })
    @Html.ActionLink("Checkout", "Checkout", "Cart", null, new { @class = "btn btn-default btn-primary" })
</div>

AdventureWorksStore.WebUI/Views/Cart/Summary.cshtml
@model AdventureWorksStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Checkout", "Cart", new { returnUrl = Request.Url.PathAndQuery }, new { @class = "btn btn-default navbar-btn" })
</div>
<div class="navbar-text navbar-right">
    <b>Your Cart:</b> @Model.CartItems.Count() Items
    @Model.ComputeTotalValue().ToString("c");
</div>

AdventureWorksStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>
@Html.ActionLink("Home", "List", "Product", null, new { @class = "btn btn-default  btn-block btn-lg" })
@foreach (var category in Model)
{
    @Html.RouteLink(category, new { controller = "Product", action = "List", page = 1, category = category }, new { @class = "btn btn-default  btn-block btn-lg" + (category == ViewBag.Category ? " btn-primary" : "") })
}

AdventureWorksStore.WebUI/Views/Product/List.cshtml
@{
    ViewBag.Title = "List";
}
@model AdventureWorksStore.WebUI.Models.ProductsListViewModel

@foreach (var m in Model.Products)
{
    @Html.Partial("ProductSummary", m);
}
<div class="pull-right btn-group">
    @Html.PageLinks(Model.PageInfo, s => Url.Action("List", new { page = s, category = Model.CurrentCategory }))
</div>

AdventureWorksStore.WebUI/Views/Shared/ProductSummary.cshtml
@model AdventureWorksStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.ListPrice.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(s => s.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add To Cart" />
        </div>
    }
    <span class="lead">@Model.Description</span>

</div>

AdventureWorksStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @Html.ActionLink("AdventureWorksStore", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
    </div>

    <div class="container body-content">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
        <hr />
    </div>
    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

AdventureWorksStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("AdventureWorksStore", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.Action("Summary", "Cart")
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
        <hr />
    </div>
    <footer class="text-center">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>